name:                forsyde-sadf-examples
version:             0.1.0.0
github:              "ricardobonna/forsyde-sadf-examples"
license:             BSD3
author:              "Ricardo Bonna"
maintainer:          "rbonna@fem.unicamp.br"
copyright:           "2018 Ricardo Bonna"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/forsyde-sadf-examples#readme>

dependencies:
- base >= 4.5 && < 5
- matrix
- forsyde-shallow >= 3.3.3.0

library:
  source-dirs: src

executables:
  forsyde-sadf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - forsyde-sadf-examples

tests:
  forsyde-sadf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - forsyde-sadf-examples
